import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "../../components/ThemeToggle";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SwitchLanguage from "../../components/SwitchLanguage";
import { Providers } from "../../redux/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {/* Dark/light toggle button */}
          <section id="features-toggle">
            <div>
              <SwitchLanguage />
            </div>
              <ThemeToggle />
            <div>
            </div>
          </section>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
